### ISSUE TITLE
TimoCloud wirft NullPointer

### ISSUE THREAD

**Issue by JeyVDW** [TimoCloud/TimoCloud-6.0#24]
Describe the bug
Nach einiger Zeit kommt die Fehlermeldung. Mit der API greife ich z. B. beim IPBann auf alle Spieler des gesamten Netzwerks zu, wobei dann ebenhalt ein Folgefehler kommt und alles, wobei ich die API verwende, nichts mehr davon klappt und alles eine NullPointer wirft.
Fehlermeldung von TimoCloud: https://paste.timo.cloud/zasitiwiwo.md

```
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: Uncaught exception while firing event:
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: java.lang.reflect.InvocationTargetException
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at java.lang.reflect.Method.invoke(Method.java:498)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.api.implementations.managers.EventManager.fireEvent(EventManager.java:45)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.api.implementations.managers.EventManager.callEvent(EventManager.java:33)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.bungeecord.sockets.BungeeStringHandler.handleMessage(BungeeStringHandler.java:44)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:15)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:9)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at java.lang.Thread.run(Thread.java:748)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: Caused by: java.lang.NullPointerException
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: at cloud.timo.TimoCloud.api.implementations.listeners.TimoCloudUniversalAPIStorageUpdateListener.onPlayerConnectEvent(TimoCloudUniversalAPIStorageUpdateListener.java:107)
[00:03:52] [epollEventLoopGroup-2-1/ERROR]: ... 37 more<
```

Mein Folgefehler (in diesem Falle ist es nicht direkt eine NullPointer, allerdings gibt die Liste TimoCloudAPI.getUniversalAPI().getPlayers() null zurück): https://paste.timo.cloud/ubareyizuj.sql

```
[01:23:18 INFO]: An internal error occurred whilst executing this command, please check the console log for details.
[01:23:18 WARN]: Error in dispatching command
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_252]
at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_252]
at de.buildcube.system.bungee.utils.ban.IPBanManager.banIP(IPBanManager.java:38) ~[?:?]
at de.buildcube.system.bungee.utils.ban.BanManager.ban(BanManager.java:54) ~[?:?]
at de.buildcube.system.bungee.commands.CMDban.execute(CMDban.java:104) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:197) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]<
```

In meinem Fall ist es z. B., wenn ich danach die IP von einem Spieler banne und dabei einmal alle Spieler durchgehe, um zu gucken, ob noch jemand dieselbe IP-Adresse hat.

for (PlayerObject playerObject : TimoCloudAPI.getUniversalAPI().getPlayers()) ... mein Code
Um den Fehler zu beheben, reicht es bei mir nicht immer aus, nur die Proxies neuzustarten, sondern muss ich oft das ganze Netzwerk.

**Comment by meerpaluten** [comment]
Kickst du direkt den spieler wärend du for (PlayerObject playerObject : TimoCloudAPI.getUniversalAPI().getPlayers()) ausführst? Wenn ja, dann must du dies änder, da dies eine ConcurrentModificationException auslöhst. Weil du ja die players änders wärend du über sie gehst, das mag java nicht.

**Comment by meerpaluten** [comment]
Speicher dir ambesten die spieler einmal in einer collection ab und kick sie danach.
